export type Difficulty = 'Fácil' | 'Médio' | 'Difícil';
export type Testament = 'Antigo' | 'Novo';
export type Category = 'Pentateuco' | 'Históricos' | 'Poéticos' | 'Profetas' | 'Evangelhos' | 'Atos' | 'Cartas' | 'Apocalipse';

export type BibleQuestion = {
  id: number;
  question: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
  reference: string;
  difficulty: Difficulty;
  testament: Testament;
  category: Category;
};

export const gameQuestions: BibleQuestion[] = [
  { id:1, question:'Quem construiu a arca antes do dilúvio?', options:['Abraão','Noé','Moisés','Jacó'], answer:1, explanation:'Deus orientou Noé a construir a arca para preservar sua família e os animais.', reference:'Gênesis 6:13–22', difficulty:'Fácil', testament:'Antigo', category:'Pentateuco' },
  { id:2, question:'Em qual jardim Adão e Eva foram colocados?', options:['Getsêmani','Éden','Carmelo','Hebrom'], answer:1, explanation:'O relato da criação identifica o lugar preparado por Deus como o jardim do Éden.', reference:'Gênesis 2:8', difficulty:'Fácil', testament:'Antigo', category:'Pentateuco' },
  { id:3, question:'Quem recebeu os Dez Mandamentos no monte Sinai?', options:['Josué','Arão','Moisés','Samuel'], answer:2, explanation:'Moisés recebeu de Deus as tábuas da aliança no Sinai.', reference:'Êxodo 31:18', difficulty:'Fácil', testament:'Antigo', category:'Pentateuco' },
  { id:4, question:'Quem interpretou os sonhos de Faraó no Egito?', options:['José','Isaque','Calebe','Arão'], answer:0, explanation:'José explicou que os sonhos anunciavam anos de fartura seguidos por fome.', reference:'Gênesis 41:25–32', difficulty:'Fácil', testament:'Antigo', category:'Pentateuco' },
  { id:5, question:'Qual alimento apareceu no deserto para sustentar Israel?', options:['Maná','Lentilhas','Figos','Uvas'], answer:0, explanation:'O povo chamou de maná o alimento que Deus providenciou no deserto.', reference:'Êxodo 16:14–15,31', difficulty:'Fácil', testament:'Antigo', category:'Pentateuco' },
  { id:6, question:'Quem sucedeu Moisés na liderança de Israel?', options:['Calebe','Josué','Gideão','Arão'], answer:1, explanation:'Josué foi comissionado para conduzir o povo à terra prometida.', reference:'Josué 1:1–6', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:7, question:'Qual cidade teve suas muralhas derrubadas após Israel marchar ao redor dela?', options:['Jerusalém','Jericó','Betel','Samaria'], answer:1, explanation:'As muralhas de Jericó caíram após o povo cumprir a orientação recebida.', reference:'Josué 6:15–20', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:8, question:'Qual juiz ficou conhecido por sua força extraordinária?', options:['Gideão','Jefté','Sansão','Otniel'], answer:2, explanation:'A história de Sansão e de sua força é narrada em Juízes 13–16.', reference:'Juízes 13–16', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:9, question:'Quem derrotou Golias com uma funda e uma pedra?', options:['Saul','Davi','Jônatas','Abner'], answer:1, explanation:'Davi enfrentou Golias confiando no Senhor e o venceu com uma pedra lançada pela funda.', reference:'1 Samuel 17:45–50', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:10, question:'Qual rei pediu sabedoria a Deus?', options:['Saul','Davi','Salomão','Josias'], answer:2, explanation:'Salomão pediu discernimento para governar, e seu pedido agradou a Deus.', reference:'1 Reis 3:5–12', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:11, question:'Qual profeta enfrentou os profetas de Baal no monte Carmelo?', options:['Eliseu','Elias','Isaías','Miquéias'], answer:1, explanation:'Elias desafiou os profetas de Baal, e o Senhor respondeu com fogo.', reference:'1 Reis 18:20–39', difficulty:'Médio', testament:'Antigo', category:'Históricos' },
  { id:12, question:'Qual rainha arriscou a própria vida para interceder pelos judeus?', options:['Vasti','Ester','Jezabel','Bate-Seba'], answer:1, explanation:'Ester decidiu entrar na presença do rei para interceder por seu povo.', reference:'Ester 4:13–16; 5:1–3', difficulty:'Fácil', testament:'Antigo', category:'Históricos' },
  { id:13, question:'Quem liderou a reconstrução dos muros de Jerusalém?', options:['Esdras','Neemias','Zorobabel','Mardoqueu'], answer:1, explanation:'Neemias liderou a reconstrução dos muros em meio a forte oposição.', reference:'Neemias 2:17–20; 6:15', difficulty:'Médio', testament:'Antigo', category:'Históricos' },
  { id:14, question:'Qual salmo começa declarando que o Senhor é o pastor do salmista?', options:['Salmo 1','Salmo 23','Salmo 91','Salmo 119'], answer:1, explanation:'O Salmo 23 usa a figura do pastor para falar do cuidado e direção do Senhor.', reference:'Salmo 23:1', difficulty:'Fácil', testament:'Antigo', category:'Poéticos' },
  { id:15, question:'Qual livro contém a frase “Tudo tem o seu tempo determinado”?', options:['Provérbios','Eclesiastes','Cantares','Jó'], answer:1, explanation:'A conhecida reflexão sobre tempos e estações aparece em Eclesiastes 3.', reference:'Eclesiastes 3:1', difficulty:'Médio', testament:'Antigo', category:'Poéticos' },
  { id:16, question:'Qual é o capítulo mais longo do livro de Salmos?', options:['23','51','91','119'], answer:3, explanation:'O Salmo 119 possui 176 versículos e uma estrutura alfabética.', reference:'Salmo 119', difficulty:'Médio', testament:'Antigo', category:'Poéticos' },
  { id:17, question:'Quem foi lançado na cova dos leões?', options:['Elias','Daniel','Jeremias','Ezequiel'], answer:1, explanation:'Daniel foi lançado na cova por manter sua prática de oração, mas Deus o preservou.', reference:'Daniel 6:16–23', difficulty:'Fácil', testament:'Antigo', category:'Profetas' },
  { id:18, question:'Qual profeta foi engolido por um grande peixe?', options:['Jonas','Amós','Joel','Oséias'], answer:0, explanation:'Jonas permaneceu no ventre de um grande peixe depois de tentar fugir de sua missão.', reference:'Jonas 1:17', difficulty:'Fácil', testament:'Antigo', category:'Profetas' },
  { id:19, question:'Qual profeta teve a visão de um vale de ossos secos?', options:['Jeremias','Ezequiel','Daniel','Zacarias'], answer:1, explanation:'Ezequiel viu um vale de ossos secos que receberam vida pela palavra do Senhor.', reference:'Ezequiel 37:1–14', difficulty:'Médio', testament:'Antigo', category:'Profetas' },
  { id:20, question:'Qual profeta anunciou que o governante de Israel sairia de Belém?', options:['Miquéias','Naum','Habacuque','Sofonias'], answer:0, explanation:'Miquéias aponta Belém Efrata no anúncio do futuro governante.', reference:'Miquéias 5:2', difficulty:'Difícil', testament:'Antigo', category:'Profetas' },
  { id:21, question:'Qual profeta declarou “Eis-me aqui, envia-me a mim”?', options:['Jeremias','Isaías','Ezequiel','Amós'], answer:1, explanation:'Isaías respondeu ao chamado após sua visão do Senhor no templo.', reference:'Isaías 6:8', difficulty:'Médio', testament:'Antigo', category:'Profetas' },
  { id:22, question:'Qual profeta era boieiro e cultivador de sicômoros?', options:['Amós','Naum','Ageu','Malaquias'], answer:0, explanation:'Amós descreveu sua ocupação antes de ser chamado para profetizar.', reference:'Amós 7:14–15', difficulty:'Difícil', testament:'Antigo', category:'Profetas' },
  { id:23, question:'Em qual cidade Jesus nasceu?', options:['Nazaré','Jerusalém','Belém','Cafarnaum'], answer:2, explanation:'Os Evangelhos situam o nascimento de Jesus em Belém da Judeia.', reference:'Mateus 2:1; Lucas 2:4–7', difficulty:'Fácil', testament:'Novo', category:'Evangelhos' },
  { id:24, question:'Quem batizou Jesus no rio Jordão?', options:['Pedro','João Batista','André','Tiago'], answer:1, explanation:'Jesus foi ao Jordão para ser batizado por João.', reference:'Mateus 3:13–17', difficulty:'Fácil', testament:'Novo', category:'Evangelhos' },
  { id:25, question:'Qual foi o primeiro sinal de Jesus narrado no Evangelho de João?', options:['Multiplicação dos pães','Cura de um cego','Água em vinho','Acalmar a tempestade'], answer:2, explanation:'Em Caná, Jesus transformou água em vinho; João o apresenta como o primeiro de seus sinais.', reference:'João 2:1–11', difficulty:'Médio', testament:'Novo', category:'Evangelhos' },
  { id:26, question:'Quem andou sobre as águas em direção a Jesus?', options:['João','Pedro','Tomé','Filipe'], answer:1, explanation:'Pedro saiu do barco e caminhou sobre as águas em direção a Jesus.', reference:'Mateus 14:28–31', difficulty:'Fácil', testament:'Novo', category:'Evangelhos' },
  { id:27, question:'Quem subiu numa árvore para conseguir ver Jesus?', options:['Bartimeu','Zaqueu','Nicodemos','Jairo'], answer:1, explanation:'Zaqueu subiu numa figueira brava porque era de baixa estatura.', reference:'Lucas 19:1–5', difficulty:'Fácil', testament:'Novo', category:'Evangelhos' },
  { id:28, question:'Qual discípulo quis ver as marcas dos cravos antes de crer na ressurreição?', options:['Tomé','Mateus','Bartolomeu','Simão'], answer:0, explanation:'Tomé expressou sua dúvida e depois encontrou Jesus ressuscitado.', reference:'João 20:24–29', difficulty:'Médio', testament:'Novo', category:'Evangelhos' },
  { id:29, question:'Quem ajudou a carregar a cruz de Jesus?', options:['José de Arimateia','Simão de Cirene','Nicodemos','Barrabás'], answer:1, explanation:'Simão de Cirene foi constrangido a carregar a cruz atrás de Jesus.', reference:'Lucas 23:26', difficulty:'Médio', testament:'Novo', category:'Evangelhos' },
  { id:30, question:'Qual Evangelho começa com “No princípio era o Verbo”?', options:['Mateus','Marcos','Lucas','João'], answer:3, explanation:'O prólogo de João apresenta o Verbo que estava com Deus e era Deus.', reference:'João 1:1', difficulty:'Fácil', testament:'Novo', category:'Evangelhos' },
  { id:31, question:'Quem foi escolhido para ocupar o lugar deixado por Judas Iscariotes?', options:['Barnabé','Matias','Silas','Estêvão'], answer:1, explanation:'Após oração e sorteio, Matias foi contado com os onze apóstolos.', reference:'Atos 1:23–26', difficulty:'Médio', testament:'Novo', category:'Atos' },
  { id:32, question:'Em qual festa o Espírito Santo foi derramado sobre os discípulos em Atos 2?', options:['Páscoa','Pentecostes','Purim','Tabernáculos'], answer:1, explanation:'O derramamento descrito em Atos 2 ocorreu no dia de Pentecostes.', reference:'Atos 2:1–4', difficulty:'Médio', testament:'Novo', category:'Atos' },
  { id:33, question:'Quem foi o primeiro mártir cristão mencionado em Atos?', options:['Tiago','Estêvão','Filipe','Ananias'], answer:1, explanation:'Estêvão foi apedrejado após seu testemunho diante do Sinédrio.', reference:'Atos 6–7', difficulty:'Médio', testament:'Novo', category:'Atos' },
  { id:34, question:'Em qual caminho Saulo teve o encontro que marcou sua conversão?', options:['Jericó','Damasco','Emaús','Antioquia'], answer:1, explanation:'Saulo viajava para Damasco quando foi cercado por uma luz do céu.', reference:'Atos 9:1–9', difficulty:'Fácil', testament:'Novo', category:'Atos' },
  { id:35, question:'Em qual cidade os discípulos foram chamados cristãos pela primeira vez?', options:['Jerusalém','Éfeso','Antioquia','Corinto'], answer:2, explanation:'Atos registra que em Antioquia os discípulos foram chamados cristãos pela primeira vez.', reference:'Atos 11:26', difficulty:'Médio', testament:'Novo', category:'Atos' },
  { id:36, question:'Qual centurião recebeu Pedro em sua casa em Atos 10?', options:['Cornélio','Júlio','Cláudio','Sérgio'], answer:0, explanation:'Cornélio recebeu Pedro após ambos serem orientados por Deus.', reference:'Atos 10:1–48', difficulty:'Médio', testament:'Novo', category:'Atos' },
  { id:37, question:'Qual capítulo de 1 Coríntios é conhecido por sua reflexão sobre o amor?', options:['7','11','13','15'], answer:2, explanation:'1 Coríntios 13 descreve características e a permanência do amor.', reference:'1 Coríntios 13', difficulty:'Fácil', testament:'Novo', category:'Cartas' },
  { id:38, question:'Qual item da armadura de Deus é associado à fé?', options:['Capacete','Escudo','Couraça','Cinto'], answer:1, explanation:'Efésios orienta os cristãos a tomarem o escudo da fé.', reference:'Efésios 6:16', difficulty:'Médio', testament:'Novo', category:'Cartas' },
  { id:39, question:'Qual fruto do Espírito aparece primeiro na lista de Gálatas 5?', options:['Paz','Domínio próprio','Amor','Alegria'], answer:2, explanation:'A lista começa com amor, seguido de alegria, paz e outras virtudes.', reference:'Gálatas 5:22–23', difficulty:'Médio', testament:'Novo', category:'Cartas' },
  { id:40, question:'Qual carta afirma que a fé sem obras é morta?', options:['Romanos','Tiago','Judas','1 Pedro'], answer:1, explanation:'Tiago ensina que uma fé sem expressão prática é morta.', reference:'Tiago 2:17', difficulty:'Médio', testament:'Novo', category:'Cartas' },
  { id:41, question:'Qual carta contém o conhecido “capítulo da fé”?', options:['Romanos','Hebreus','1 João','2 Timóteo'], answer:1, explanation:'Hebreus 11 relembra personagens do Antigo Testamento como exemplos de fé.', reference:'Hebreus 11', difficulty:'Médio', testament:'Novo', category:'Cartas' },
  { id:42, question:'A qual cooperador Paulo escreveu duas cartas pastorais?', options:['Tito','Timóteo','Barnabé','Apolo'], answer:1, explanation:'O Novo Testamento contém 1 e 2 Timóteo, cartas de Paulo a seu cooperador.', reference:'1 Timóteo 1:1–2; 2 Timóteo 1:1–2', difficulty:'Fácil', testament:'Novo', category:'Cartas' },
  { id:43, question:'Qual livro trata do retorno de um homem chamado Onésimo?', options:['Judas','Filemom','Tito','2 João'], answer:1, explanation:'Paulo escreve a Filemom intercedendo por Onésimo.', reference:'Filemom 10–17', difficulty:'Difícil', testament:'Novo', category:'Cartas' },
  { id:44, question:'Quem é chamado por Paulo de “médico amado”?', options:['Lucas','Marcos','Tito','Silas'], answer:0, explanation:'Paulo chama Lucas de médico amado nas saudações de Colossenses.', reference:'Colossenses 4:14', difficulty:'Difícil', testament:'Novo', category:'Cartas' },
  { id:45, question:'Em qual ilha João estava quando recebeu as visões do Apocalipse?', options:['Creta','Chipre','Patmos','Malta'], answer:2, explanation:'João declara estar na ilha de Patmos por causa da palavra de Deus.', reference:'Apocalipse 1:9', difficulty:'Médio', testament:'Novo', category:'Apocalipse' },
  { id:46, question:'Quantas igrejas recebem mensagens específicas em Apocalipse 2 e 3?', options:['5','7','10','12'], answer:1, explanation:'As mensagens são dirigidas a sete igrejas da Ásia.', reference:'Apocalipse 1:11; 2–3', difficulty:'Fácil', testament:'Novo', category:'Apocalipse' },
  { id:47, question:'Qual igreja do Apocalipse é repreendida por ser “morna”?', options:['Éfeso','Filadélfia','Laodiceia','Esmirna'], answer:2, explanation:'A mensagem a Laodiceia usa a figura da água morna para censurar sua condição.', reference:'Apocalipse 3:14–22', difficulty:'Médio', testament:'Novo', category:'Apocalipse' },
  { id:48, question:'Qual é o último livro da Bíblia no cânon protestante?', options:['Judas','Hebreus','Apocalipse','Malaquias'], answer:2, explanation:'Apocalipse encerra o Novo Testamento e o cânon protestante de 66 livros.', reference:'Apocalipse', difficulty:'Fácil', testament:'Novo', category:'Apocalipse' },
];
