export type Difficulty = 'Fácil' | 'Médio' | 'Difícil';
export type Testament = 'Antigo' | 'Novo';
export type Category = 'Pentateuco' | 'Históricos' | 'Poéticos' | 'Profetas' | 'Evangelhos' | 'Atos' | 'Cartas' | 'Apocalipse';

export type BibleQuestion = {
  id: number;
  question: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
  reference: string;
  difficulty: Difficulty;
  testament: Testament;
  category: Category;
};

export const VERBO_QUESTIONS: BibleQuestion[] = [
  { id: 1, question: 'Quem construiu a arca para escapar do dilúvio?', options: ['Abraão','Noé','Moisés','Davi'], answer: 1, explanation: 'Deus orientou Noé a construir a arca para preservar sua família e representantes dos animais.', reference: 'Gênesis 6:13–22', difficulty: 'Fácil', testament: 'Antigo', category: 'Pentateuco' },
  { id: 2, question: 'Qual foi o sinal da aliança de Deus com Noé após o dilúvio?', options: ['Uma estrela','Uma coluna de fogo','O arco-íris','Uma oliveira'], answer: 2, explanation: 'Deus colocou o arco nas nuvens como sinal da aliança estabelecida após o dilúvio.', reference: 'Gênesis 9:12–17', difficulty: 'Fácil', testament: 'Antigo', category: 'Pentateuco' },
  { id: 3, question: 'Quem foi chamado por Deus para sair de sua terra e ir para uma terra que Ele mostraria?', options: ['Isaque','Jacó','Abraão','José'], answer: 2, explanation: 'Abrão recebeu o chamado de Deus para deixar sua terra e seguir pela fé.', reference: 'Gênesis 12:1–4', difficulty: 'Fácil', testament: 'Antigo', category: 'Pentateuco' },
  { id: 4, question: 'Quem recebeu os Dez Mandamentos no monte Sinai?', options: ['Josué','Moisés','Arão','Calebe'], answer: 1, explanation: 'Moisés recebeu de Deus as tábuas da aliança no monte Sinai.', reference: 'Êxodo 31:18', difficulty: 'Fácil', testament: 'Antigo', category: 'Pentateuco' },
  { id: 5, question: 'Qual alimento Deus forneceu diariamente a Israel no deserto?', options: ['Trigo','Maná','Figos','Lentilhas'], answer: 1, explanation: 'O maná aparecia pela manhã e sustentou o povo durante a peregrinação.', reference: 'Êxodo 16:13–18', difficulty: 'Fácil', testament: 'Antigo', category: 'Pentateuco' },
  { id: 6, question: 'Quem sucedeu Moisés na liderança de Israel?', options: ['Josué','Samuel','Gideão','Arão'], answer: 0, explanation: 'Josué foi comissionado para conduzir Israel à Terra Prometida.', reference: 'Josué 1:1–9', difficulty: 'Fácil', testament: 'Antigo', category: 'Históricos' },
  { id: 7, question: 'Qual cidade teve seus muros derrubados após Israel marchar ao redor dela?', options: ['Jerusalém','Jericó','Hebrom','Samaria'], answer: 1, explanation: 'Os muros de Jericó caíram após o povo seguir a ordem dada por Deus.', reference: 'Josué 6:15–20', difficulty: 'Fácil', testament: 'Antigo', category: 'Históricos' },
  { id: 8, question: 'Quem derrotou Golias com uma funda e uma pedra?', options: ['Saul','Jônatas','Davi','Samuel'], answer: 2, explanation: 'Davi enfrentou Golias confiando no Senhor e o derrubou com uma pedra.', reference: '1 Samuel 17:45–50', difficulty: 'Fácil', testament: 'Antigo', category: 'Históricos' },
  { id: 9, question: 'Qual rei pediu sabedoria a Deus em vez de riquezas?', options: ['Saul','Davi','Salomão','Ezequias'], answer: 2, explanation: 'Salomão pediu entendimento para governar, e seu pedido agradou a Deus.', reference: '1 Reis 3:5–14', difficulty: 'Fácil', testament: 'Antigo', category: 'Históricos' },
  { id: 10, question: 'Quem foi lançado na cova dos leões por continuar orando a Deus?', options: ['Daniel','Elias','Neemias','Esdras'], answer: 0, explanation: 'Daniel permaneceu fiel em oração e Deus fechou a boca dos leões.', reference: 'Daniel 6:10–23', difficulty: 'Fácil', testament: 'Antigo', category: 'Profetas' },
  { id: 11, question: 'Qual profeta foi engolido por um grande peixe?', options: ['Amós','Jonas','Miquéias','Joel'], answer: 1, explanation: 'Jonas foi lançado ao mar e Deus preparou um grande peixe para o acolher.', reference: 'Jonas 1:15–17', difficulty: 'Fácil', testament: 'Antigo', category: 'Profetas' },
  { id: 12, question: 'Quem interpretou os sonhos do faraó no Egito?', options: ['José','Benjamim','Levi','Judá'], answer: 0, explanation: 'José explicou que os sonhos anunciavam anos de fartura seguidos por anos de fome.', reference: 'Gênesis 41:25–32', difficulty: 'Médio', testament: 'Antigo', category: 'Pentateuco' },
  { id: 13, question: 'Qual juiz de Israel ficou conhecido por sua força extraordinária?', options: ['Gideão','Jefté','Sansão','Otniel'], answer: 2, explanation: 'Sansão recebeu de Deus força incomum e atuou como juiz de Israel.', reference: 'Juízes 13–16', difficulty: 'Fácil', testament: 'Antigo', category: 'Históricos' },
  { id: 14, question: 'Quem disse: “O Senhor é o meu pastor; nada me faltará”?', options: ['Salomão','Asafe','Moisés','Davi'], answer: 3, explanation: 'O Salmo 23 é identificado como salmo de Davi.', reference: 'Salmo 23:1', difficulty: 'Fácil', testament: 'Antigo', category: 'Poéticos' },
  { id: 15, question: 'Em qual livro encontramos a frase “Tudo tem o seu tempo determinado”?', options: ['Jó','Salmos','Provérbios','Eclesiastes'], answer: 3, explanation: 'Eclesiastes 3 apresenta uma conhecida reflexão sobre os tempos da vida.', reference: 'Eclesiastes 3:1', difficulty: 'Médio', testament: 'Antigo', category: 'Poéticos' },
  { id: 16, question: 'Quem confrontou os profetas de Baal no monte Carmelo?', options: ['Eliseu','Isaías','Elias','Jeremias'], answer: 2, explanation: 'Elias desafiou os profetas de Baal para mostrar ao povo quem era o verdadeiro Deus.', reference: '1 Reis 18:20–39', difficulty: 'Médio', testament: 'Antigo', category: 'Históricos' },
  { id: 17, question: 'Qual profeta teve a visão de um vale de ossos secos?', options: ['Ezequiel','Daniel','Oséias','Zacarias'], answer: 0, explanation: 'Ezequiel viu ossos secos receberem vida em uma visão sobre restauração.', reference: 'Ezequiel 37:1–14', difficulty: 'Médio', testament: 'Antigo', category: 'Profetas' },
  { id: 18, question: 'Quem reconstruiu os muros de Jerusalém após o exílio?', options: ['Esdras','Neemias','Zorobabel','Mardoqueu'], answer: 1, explanation: 'Neemias liderou a reconstrução dos muros apesar da oposição.', reference: 'Neemias 2–6', difficulty: 'Médio', testament: 'Antigo', category: 'Históricos' },
  { id: 19, question: 'Qual rainha arriscou a própria vida para interceder pelo povo judeu?', options: ['Rute','Ester','Bate-Seba','Mical'], answer: 1, explanation: 'Ester apresentou-se ao rei para interceder por seu povo diante do decreto de extermínio.', reference: 'Ester 4:13–16; 5:1–3', difficulty: 'Médio', testament: 'Antigo', category: 'Históricos' },
  { id: 20, question: 'Segundo Isaías 6, o que os serafins proclamavam diante do Senhor?', options: ['Aleluia','Santo, santo, santo','Hosana nas alturas','Grande é o Senhor'], answer: 1, explanation: 'Na visão do trono, os serafins proclamavam a santidade de Deus.', reference: 'Isaías 6:1–3', difficulty: 'Difícil', testament: 'Antigo', category: 'Profetas' },
  { id: 21, question: 'Em qual cidade Jesus nasceu?', options: ['Nazaré','Jerusalém','Belém','Cafarnaum'], answer: 2, explanation: 'Jesus nasceu em Belém da Judeia nos dias do rei Herodes.', reference: 'Mateus 2:1', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 22, question: 'Quem batizou Jesus no rio Jordão?', options: ['Pedro','João Batista','André','Tiago'], answer: 1, explanation: 'Jesus foi da Galileia ao Jordão para ser batizado por João.', reference: 'Mateus 3:13–17', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 23, question: 'Qual foi o primeiro milagre de Jesus registrado no Evangelho de João?', options: ['Multiplicação dos pães','Cura de um cego','Água transformada em vinho','Pesca maravilhosa'], answer: 2, explanation: 'Em Caná da Galileia, Jesus transformou água em vinho.', reference: 'João 2:1–11', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 24, question: 'Quantos apóstolos Jesus escolheu?', options: ['7','10','12','14'], answer: 2, explanation: 'Jesus chamou doze discípulos e os designou apóstolos.', reference: 'Lucas 6:12–16', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 25, question: 'Quem negou Jesus três vezes antes do galo cantar?', options: ['Pedro','Tomé','Filipe','Bartolomeu'], answer: 0, explanation: 'Pedro negou conhecer Jesus três vezes, como Jesus havia anunciado.', reference: 'Lucas 22:54–62', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 26, question: 'Quem subiu em uma árvore para conseguir ver Jesus passar?', options: ['Nicodemos','Zaqueu','Bartimeu','Jairo'], answer: 1, explanation: 'Zaqueu subiu em um sicômoro por ser de pequena estatura e querer ver Jesus.', reference: 'Lucas 19:1–6', difficulty: 'Fácil', testament: 'Novo', category: 'Evangelhos' },
  { id: 27, question: 'Qual discípulo disse que precisava ver as marcas dos cravos para crer na ressurreição?', options: ['André','João','Tomé','Mateus'], answer: 2, explanation: 'Tomé declarou que precisaria ver e tocar as marcas para crer.', reference: 'João 20:24–29', difficulty: 'Médio', testament: 'Novo', category: 'Evangelhos' },
  { id: 28, question: 'Quem foi escolhido para substituir Judas Iscariotes entre os doze?', options: ['Barnabé','Matias','Silas','Estêvão'], answer: 1, explanation: 'Após oração e lançamento de sortes, Matias foi contado com os onze apóstolos.', reference: 'Atos 1:23–26', difficulty: 'Médio', testament: 'Novo', category: 'Atos' },
  { id: 29, question: 'Quem foi o primeiro mártir cristão mencionado em Atos?', options: ['Tiago','Estêvão','Filipe','Ananias'], answer: 1, explanation: 'Estêvão foi apedrejado após testemunhar diante do Sinédrio.', reference: 'Atos 7:54–60', difficulty: 'Médio', testament: 'Novo', category: 'Atos' },
  { id: 30, question: 'Em qual caminho Saulo teve o encontro que transformou sua vida?', options: ['Caminho de Jerusalém','Caminho de Damasco','Caminho de Emaús','Caminho de Antioquia'], answer: 1, explanation: 'Saulo seguia para Damasco quando uma luz do céu o cercou e ele ouviu a voz de Jesus.', reference: 'Atos 9:1–9', difficulty: 'Fácil', testament: 'Novo', category: 'Atos' },
  { id: 31, question: 'Quem recebeu Pedro em Cesareia após uma visão que preparou o encontro?', options: ['Cornélio','Lídia','Ágabo','Sérgio Paulo'], answer: 0, explanation: 'Cornélio, um centurião temente a Deus, recebeu Pedro em sua casa.', reference: 'Atos 10', difficulty: 'Médio', testament: 'Novo', category: 'Atos' },
  { id: 32, question: 'Qual casal cantava e orava na prisão quando houve um terremoto?', options: ['Pedro e João','Paulo e Barnabé','Paulo e Silas','Barnabé e Marcos'], answer: 2, explanation: 'Paulo e Silas oravam e cantavam hinos quando um terremoto abriu as portas da prisão.', reference: 'Atos 16:25–26', difficulty: 'Médio', testament: 'Novo', category: 'Atos' },
  { id: 33, question: 'Segundo 1 Coríntios 13, o que permanece junto com a fé e a esperança?', options: ['Sabedoria','Poder','Amor','Conhecimento'], answer: 2, explanation: 'Paulo conclui que permanecem fé, esperança e amor, sendo o amor o maior deles.', reference: '1 Coríntios 13:13', difficulty: 'Fácil', testament: 'Novo', category: 'Cartas' },
  { id: 34, question: 'Em qual carta encontramos a “armadura de Deus”?', options: ['Romanos','Efésios','Filipenses','Colossenses'], answer: 1, explanation: 'Paulo usa a imagem da armadura para ensinar sobre firmeza espiritual.', reference: 'Efésios 6:10–18', difficulty: 'Médio', testament: 'Novo', category: 'Cartas' },
  { id: 35, question: 'Qual fruto do Espírito aparece primeiro na lista de Gálatas 5?', options: ['Paz','Alegria','Amor','Mansidão'], answer: 2, explanation: 'A lista do fruto do Espírito começa com amor, seguido de alegria e paz.', reference: 'Gálatas 5:22–23', difficulty: 'Médio', testament: 'Novo', category: 'Cartas' },
  { id: 36, question: 'Qual carta contém a frase “Posso todas as coisas naquele que me fortalece”?', options: ['Romanos','Filipenses','Hebreus','Tiago'], answer: 1, explanation: 'Paulo fala sobre aprender a viver contente em toda circunstância e declara sua suficiência em Cristo.', reference: 'Filipenses 4:11–13', difficulty: 'Fácil', testament: 'Novo', category: 'Cartas' },
  { id: 37, question: 'Quem é citado em Hebreus como alguém que ofereceu a Deus um sacrifício superior ao de Caim?', options: ['Sete','Enoque','Abel','Noé'], answer: 2, explanation: 'Hebreus apresenta Abel como exemplo de fé ao oferecer sacrifício superior.', reference: 'Hebreus 11:4', difficulty: 'Difícil', testament: 'Novo', category: 'Cartas' },
  { id: 38, question: 'Segundo Tiago, o que deve fazer quem tem falta de sabedoria?', options: ['Esperar em silêncio','Pedir a Deus','Consultar os mais velhos apenas','Jejuar sete dias'], answer: 1, explanation: 'Tiago ensina que quem necessita de sabedoria deve pedi-la a Deus, que dá generosamente.', reference: 'Tiago 1:5', difficulty: 'Médio', testament: 'Novo', category: 'Cartas' },
  { id: 39, question: 'Em qual ilha João recebeu a visão registrada em Apocalipse?', options: ['Creta','Malta','Patmos','Chipre'], answer: 2, explanation: 'João afirma estar na ilha chamada Patmos por causa da Palavra de Deus e do testemunho de Jesus.', reference: 'Apocalipse 1:9', difficulty: 'Médio', testament: 'Novo', category: 'Apocalipse' },
  { id: 40, question: 'Quantas igrejas da Ásia recebem mensagens no início do Apocalipse?', options: ['5','7','10','12'], answer: 1, explanation: 'Apocalipse 2–3 registra mensagens dirigidas a sete igrejas da Ásia.', reference: 'Apocalipse 1:4, 11; 2–3', difficulty: 'Fácil', testament: 'Novo', category: 'Apocalipse' }
];
